export type MasterProdi = {
  prodiId: string;
  kode?: string;
  nama: string;
  displayName: string;
  jenjang?: string;
  jurusan?: string;
  isActive: boolean;
  createdAt?: number;
  updatedAt?: number;
  syncedAt?: number | object;
  source?: string;
};

export type FaceApiMatrix = {
  model: "face-api.js" | string;
  modelName?: string;
  descriptorSize: number;
  descriptor?: number[];
  descriptors?: number[][];
  matrix?: number[];
  matrixRows?: number;
  matrixCols?: number;
  metric?: "euclidean" | string;
  distanceThreshold?: number;
  createdAt?: number;
  updatedAt?: number;
};

export type RegisteredFace = {
  nodeKey: string;
  name: string;
  nameKey: string;
  faceId: string;
  jabatan: string;
  prodi: string;
  prodiId?: string;
  prodiName?: string;
  descriptor?: number[];
  descriptors?: number[][];
  descriptorSize?: number;
  descriptorModel?: "face-api.js" | string;
  matrix?: number[];
  matrixRows?: number;
  matrixCols?: number;
  faceApi?: FaceApiMatrix;
  hasSignature?: boolean;
  signatureBase64?: string;
  signatureMimeType?: string;
  signatureUpdatedAt?: number | null;
  hasFaceThumbnail?: boolean;
  faceThumbnailBase64?: string;
  faceThumbnailMimeType?: string;
  faceThumbnailUpdatedAt?: number | null;
  createdAt?: number;
  updatedAt?: number;
  syncedAt?: number;
  source?: string;
};

export type MeetingInfoForm = {
  formId: string;
  noDokumen?: string;
  meetingName: string;
  topikRapat?: string;
  agendaRapat?: string;
  tanggal: string;
  hari?: string;
  tempat?: string;
  waktuMulai?: string;
  waktuSelesai?: string;
  waktu?: string;
  pemimpinRapat?: string;
  notulis?: string;
  prodiIds?: string[];
  prodiNames?: string[];
  prodiText?: string;
  pesertaText?: string;
  catatan?: string;
  status?: "draft" | "scheduled" | "started" | "cancelled" | string;
  meetingId?: string;
  meetingDate?: number;
  meetingDateKey?: string;
  createdAt?: number;
  updatedAt?: number;
  syncedAt?: number;
  source?: string;
};

export type MeetingRunForm = {
  agendaRapat?: string;
  pembahasan?: string;
  hasilRapat?: string;
  catatan?: string;
  catatanTambahan?: string;
  tindakLanjut?: string;
  pemimpinRapat?: string;
  notulis?: string;
  startedAt?: number;
  finishedAt?: number | null;
  updatedAt?: number;
  status?: "active" | "closed" | string;
};

export type Meeting = {
  meetingId: string;
  meetingName: string;
  noDokumen?: string;
  meetingImageUrl?: string;
  meetingImageBase64?: string;
  meetingImagePath?: string;
  meetingImageFileName?: string;
  meetingImageMimeType?: string;
  meetingImageSize?: number;
  meetingImageUpdatedAt?: number | null;
  meetingImageStorage?: "firestore-base64" | "firebase-storage" | "vercel-blob" | "public" | string;
  catatan?: string;
  tanggal?: string;
  hari?: string;
  tempat?: string;
  waktu?: string;
  waktuMulai?: string;
  waktuSelesai?: string;
  topikRapat?: string;
  agendaRapat?: string;
  pembahasan?: string;
  hasilRapat?: string;
  catatanTambahan?: string;
  tindakLanjut?: string;
  pemimpinRapat?: string;
  notulis?: string;
  prodiIds?: string[];
  prodiNames?: string[];
  prodiText?: string;
  sourceInvitationFormId?: string;
  meetingDate?: number;
  meetingDateKey?: string;
  status?: "active" | "closed" | string;
  participantsCount?: number;
  createdAt?: number;
  updatedAt?: number;
  closedAt?: number | null;
  syncedAt?: number;
  source?: string;
  runForm?: MeetingRunForm;
  presences?: Record<string, Presence>;
};

export type Presence = {
  name: string;
  nameKey: string;
  faceId?: string;
  hasFaceThumbnail?: boolean;
  faceThumbnailBase64?: string;
  faceThumbnailMimeType?: string;
  faceThumbnailUpdatedAt?: number | null;
  jabatan?: string;
  prodi?: string;
  prodiId?: string;
  prodiName?: string;
  matched: boolean;
  score?: number;
  lastScore: number;
  distance?: number;
  method: string;
  firstCheckInAt: number;
  lastCheckInAt: number;
  createdAt: number;
  updatedAt: number;
  syncedAt?: number | object;
  source: string;
};
